apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bentopdf
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: bentopdf

  source:
    repoURL: https://kriegalex.github.io/k8s-charts/
    chart: bentopdf
    targetRevision: 1.0.1
    helm:
      values: |
        service:
          type: LoadBalancer
          loadBalancerIP: 10.2.1.103
          port: 80
          targetPort: 8080

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
