apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semaphore
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/xHomier/GitAppsRepo.git
    targetRevision: main
    path: apps/semaphore
  destination:
    server: https://kubernetes.default.svc
    namespace: semaphore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
