apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scanopy-postgres
  namespace: scanopy
spec:
  serviceName: scanopy-postgres
  replicas: 1
  selector:
    matchLabels:
      app: scanopy-postgres
  template:
    metadata:
      labels:
        app: scanopy-postgres
    spec:
      nodeSelector:
        nodepool: {{ .Values.nodepool }}

      initContainers:
        - name: init-permissions
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              mkdir -p /var/lib/postgresql/data
              chown -R 999:999 /var/lib/postgresql/data
              chmod 700 /var/lib/postgresql/data
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data

      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: scanopy-secrets
                  key: postgres_password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: data
          hostPath:
            path: /var/lib/scanopy-postgres
            type: DirectoryOrCreate
