apiVersion: v1
kind: Secret
metadata:
  name: scanopy-secrets
  namespace: scanopy
type: Opaque
stringData:
  postgres_password: "CHANGE_ME_STRONG_PASSWORD"
  daemon_api_key: "scp_d_QlRUQzcRfIQzlpSPoB5g8ltt0mKf8NVB"
